#pragma once
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
namespace stagemesh {
enum class MidiLearnMessage:std::uint8_t{note=0,control_change=1,pitch_bend=2,program=3};
enum class MidiMapBehavior:std::uint8_t{absolute=0,relative=1,trigger=2,toggle=3,gate=4};
enum class MidiMappedActionKind:std::uint8_t{automation=0,transport_play=1,transport_stop=2,transport_tempo=3,sample_trigger=4,loop_toggle=5,loop_clear=6};
struct MidiLearnBinding{std::uint64_t mapping_id{0},device_id{0},target_id{0},resource_id{0};std::uint32_t parameter_id{0};std::uint8_t channel{0},number{0},steps_per_beat{0};MidiLearnMessage message{MidiLearnMessage::control_change};MidiMapBehavior behavior{MidiMapBehavior::absolute};MidiMappedActionKind action{MidiMappedActionKind::automation};float minimum{0},maximum{1},relative_position{.5F};bool key_sync{false},enabled{true},toggle_state{false};};
struct MidiMappedAction{std::uint64_t mapping_id{0},target_id{0},resource_id{0},show_time_ns{0};std::uint32_t parameter_id{0};float value{0};std::uint8_t input_note{0},output_note{0};MidiMappedActionKind action{MidiMappedActionKind::automation};bool key_synced{false},physical_outputs_armed{false};};
template<std::size_t BindingCapacity=128,std::size_t ActionCapacity=256>class MidiLearnRouter final{
public:
 struct Status{std::uint32_t bindings{0},queued{0};std::uint64_t received{0},matched{0},dropped{0};double master_bpm{120};std::uint8_t key_root{0};std::uint16_t scale_mask{0x0AB5};bool physical_outputs_armed{false};};
 void configure_master(double bpm,std::uint8_t key_root,std::uint16_t scale_mask)noexcept{status_.master_bpm=std::clamp(bpm,30.0,300.0);status_.key_root=key_root%12;status_.scale_mask=scale_mask?static_cast<std::uint16_t>(scale_mask&0x0FFF):0x0FFF;}
 [[nodiscard]]bool upsert(MidiLearnBinding binding)noexcept{if(!binding.mapping_id||!binding.device_id||!binding.target_id||binding.channel>15||binding.number>127)return false;for(std::size_t i=0;i<count_;++i)if(bindings_[i].mapping_id==binding.mapping_id||same_source(bindings_[i],binding)){bindings_[i]=binding;status_.bindings=count_;return true;}if(count_>=BindingCapacity)return false;bindings_[count_++]=binding;status_.bindings=count_;return true;}
 bool remove(std::uint64_t mapping_id)noexcept{for(std::size_t i=0;i<count_;++i)if(bindings_[i].mapping_id==mapping_id){bindings_[i]=bindings_[--count_];status_.bindings=count_;return true;}return false;}
 void clear()noexcept{count_=0;head_=tail_=queued_=0;status_=Status{};}
 void process(std::uint64_t device,std::uint8_t status,std::uint8_t data1,std::uint8_t data2,std::uint64_t show_ns)noexcept{++status_.received;const auto high=status&0xF0U;MidiLearnMessage message{};std::uint8_t number=data1;std::uint16_t raw=data2;if(high==0x90U&&data2>0)message=MidiLearnMessage::note;else if(high==0x80U||(high==0x90U&&data2==0))return;else if(high==0xB0U)message=MidiLearnMessage::control_change;else if(high==0xE0U){message=MidiLearnMessage::pitch_bend;number=0;raw=static_cast<std::uint16_t>(data1|(data2<<7U));}else if(high==0xC0U){message=MidiLearnMessage::program;raw=data1;}else return;for(std::size_t i=0;i<count_;++i){auto&binding=bindings_[i];if(!binding.enabled||binding.device_id!=device||binding.channel!=(status&0x0FU)||binding.message!=message||binding.number!=number)continue;MidiMappedAction action{};action.mapping_id=binding.mapping_id;action.target_id=binding.target_id;action.resource_id=binding.resource_id;action.parameter_id=binding.parameter_id;action.action=binding.action;action.show_time_ns=quantize(show_ns,binding.steps_per_beat);float normalized=message==MidiLearnMessage::pitch_bend?static_cast<float>(raw)/16383.0F:static_cast<float>(raw)/127.0F;if(binding.behavior==MidiMapBehavior::relative){const int delta=raw<=63?raw:static_cast<int>(raw)-128;binding.relative_position=std::clamp(binding.relative_position+static_cast<float>(delta)/127.0F,0.0F,1.0F);normalized=binding.relative_position;}if(binding.behavior==MidiMapBehavior::toggle){binding.toggle_state=!binding.toggle_state;action.value=binding.toggle_state?1.0F:0.0F;}else if(binding.behavior==MidiMapBehavior::trigger||binding.behavior==MidiMapBehavior::gate)action.value=1.0F;else action.value=binding.minimum+(binding.maximum-binding.minimum)*normalized;if(binding.key_sync&&message==MidiLearnMessage::note){action.input_note=data1;action.output_note=nearest_key_note(data1);action.key_synced=true;}if(!push(action))++status_.dropped;else ++status_.matched;}}
 [[nodiscard]]bool pop(MidiMappedAction&out)noexcept{if(!queued_)return false;out=actions_[head_];head_=(head_+1)%ActionCapacity;--queued_;status_.queued=queued_;return true;}
 [[nodiscard]]Status status()const noexcept{return status_;}
private:
 static bool same_source(const MidiLearnBinding&a,const MidiLearnBinding&b)noexcept{return a.device_id==b.device_id&&a.channel==b.channel&&a.message==b.message&&a.number==b.number;}
 std::uint64_t quantize(std::uint64_t show_ns,std::uint8_t steps)const noexcept{if(!steps)return show_ns;const auto beat=static_cast<std::uint64_t>(60'000'000'000.0/status_.master_bpm);const auto step=std::max<std::uint64_t>(1,beat/steps);return ((show_ns+step-1)/step)*step;}
 std::uint8_t nearest_key_note(std::uint8_t note)const noexcept{for(std::uint8_t distance=0;distance<12;++distance){const int down=static_cast<int>(note)-distance,up=static_cast<int>(note)+distance;if(down>=0&&((status_.scale_mask>>((down-status_.key_root+120)%12))&1U))return static_cast<std::uint8_t>(down);if(up<=127&&((status_.scale_mask>>((up-status_.key_root+120)%12))&1U))return static_cast<std::uint8_t>(up);}return note;}
 bool push(const MidiMappedAction&action)noexcept{if(queued_>=ActionCapacity)return false;actions_[tail_]=action;tail_=(tail_+1)%ActionCapacity;++queued_;status_.queued=queued_;return true;}
 std::array<MidiLearnBinding,BindingCapacity>bindings_{};std::array<MidiMappedAction,ActionCapacity>actions_{};std::size_t count_{0},head_{0},tail_{0},queued_{0};Status status_{};
};}
